name: social_foundation
description: social foundation
version: 0.1.38
homepage: https://github.com/gohopo/social_foundation
publish_to: none

environment:
  sdk: '>=3.4.0'

dependencies:
  adaptive_dialog: 2.3.0
  audioplayers: 6.1.0
  audio_session: 0.1.21
  bot_toast: 4.1.3
  cached_network_image: 3.4.1
  crypto: 3.0.3
  common_utils: 2.1.0
  device_info_plus: 11.1.0
  dio: 5.7.0
  event_bus: 2.0.0
  extended_image: 8.3.0
  flutter:
    sdk: flutter
  flutter_cache_manager: 3.4.1
  flutter_screenutil: 5.9.3
  flutter_sound: 9.16.3
  flutter_spinkit: 5.0.0
  fluwx: 5.7.3
  get_it: 7.2.0
  image_gallery_saver:
    git:
      url: https://github.com/knottx/image_gallery_saver.git
      ref: 24fd8207a4491c42ed907060bb5bf40c2430131f
  image_picker: 1.0.3
  path: 1.9.0
  path_provider: 2.1.4
  permission_handler: 8.1.6
  provider: 6.1.2
  pull_to_refresh:
    git:
      url: https://github.com/gohopo/flutter_pulltorefresh.git
  shared_preferences: 2.2.3
  shimmer: 2.0.0
  sqflite: 2.3.3+1
  svgaplayer_flutter:
    git:
      url: https://github.com/gohopo/SVGAPlayer-Flutter.git

flutter:
  assets:
    - assets/images/
    - assets/images/audio_recorder/
  plugin:
    platforms:
      android:
        package: com.gohopo.social_foundation
        pluginClass: SocialFoundationPlugin
      ios:
        pluginClass: SocialFoundationPlugin
  uses-material-design: true
